spring:
  application:
    name: news-eureka-server

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readiness-state: #read by docker to check if the service is ready to accept traffic
      enabled: true
    liveness-state: #read by docker to check if the service is alive
      enabled: true
  endpoint:
    health:
      probes: 
        enabled: true

server:
  port: ${SERVER_PORT:8070} # default port for Eureka server

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost} # hostname for the Eureka server instance; its localhost for local system
  client:
    registerWithEureka: false # do not register eureka server with itself
    fetchRegistry: false # eureka server does not need to fetch registry for other microservices
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

